---
# Prepare Elasticsearch environment

- name: Ensure {{ es_user_home }} path exist
  file:
    path: "{{ es_user_home }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"

- name: Ensure {{ es_user_home }}/admin/nagios path exist
  file:
    path: "{{ es_user_home }}/admin/nagios"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0775

- name: Ensure {{ es_user_home }}/admin/nagios/log path exist
  file:
    path: "{{ es_user_home }}/admin/nagios/log"
    state: directory
    owner: "nrpevsc"
    group: "nagios"
    mode: 0775


