---
- name: Ensure libselinux-python on CentOS 6.x
  yum: name=libselinux-python state=present update_cache=yes
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: Install maven_artifact module requirements
  yum:
    name: python-lxml
    enablerepo: EPEL
    state: present

- name: Create tmp directory
  file:
    path: "{{ es_user_home }}/tmp"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    recurse: yes
    state: directory
  changed_when: False

- name: Download the tarball from nexus
  maven_artifact:
    group_id: elasticsearch
    artifact_id: elasticsearch
    version: "{{ es_version }}"
    extension: "tar.gz"
    dest: "{{ es_user_home }}/tmp"
    repository_url: "http://nexus/service/local/repositories/thirdparty/content"
  register: redhat_elasticsearch_install_from_repo
  # become_user: "{{ es_user }}"

- name: Create tmp directory
  file:
    path: "{{ es_home }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    recurse: yes
    state: directory

- name: Unarchive the tarball
  unarchive:
    src: "{{ es_user_home }}/tmp/{{ es_tarball }}"
    dest: "{{ es_home }}"
    remote_src: yes
    extra_opts:
      - "--strip=1"
    creates: "{{ es_home }}/LICENSE.txt"
  # become_user: "{{ es_user }}"

- name: Chown {{ es_home }}
  file:
    dest: "{{ es_home }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    recurse: yes

- name: Create centreon log directory
  file:
    state: directory
    recurse: yes
    dest: "{{ es_home }}/admin/nagios/log"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0777
