---
- name: Install maven_artifact module requirements 
  yum:
    name: python-lxml
    enablerepo: EPEL
    state: present

- name: Ensure config curator directory exists
  file:
    path: "{{ curator_home }}/config"
    state: directory
    recurse: yes
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: Ensure actions curator directory exists
  file:
    path: "{{ curator_home }}/actions"
    state: directory
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: Ensure tmp curator directory exists
  file:
    path: "{{ curator_home }}/tmp"
    state: directory
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: Ensure logs curator directory exists
  file:
    path: "{{ curator_home }}/logs"
    state: directory
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: Download the rpm from nexus
  maven_artifact:
    group_id: elasticsearch-curator
    artifact_id: elasticsearch-curator
    version: "{{ curator_version }}"
    extension: "rpm"
    dest: "{{ curator_home }}/tmp"
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    repository_url: "http://nexus/service/local/repositories/thirdparty/content"

#- name: Copy curator rpm
#  copy:
#    src: "admin_tools/{{curator_rpm }}"
#    dest: "{{ curator_home }}/tmp"
#    owner: "{{ curator_user }}"
#    group: "{{ curator_group }}"
#    mode: 0755

- name: Curator install via yum
  yum:
    name: "{{ curator_home }}/tmp/{{curator_rpm }}"
    state: present

- name: template curator config file
  template:
    src: "admin_tools/curator/curator_config.yml.j2"
    dest: "{{ curator_home }}/config/curator_config.yml"
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: create logrotate
  template:
    src: "admin_tools/curator/curator_logrotate.j2"
    dest: "/etc/logrotate.d/{{ curator_user }}_curator"

- name: Deploy yaml actions file
  template:
    src: "admin_tools/curator/curator_actions.yml.j2"
    dest: "{{ curator_home }}/actions/curator_actions.yml"
    owner: "{{ curator_user }}"
    group: "{{ curator_group }}"
    mode: 0755

- name: Set cron for Curator actions
  cron:
    name: "{{ curator_cron_job.description }}"
    month: "{{ curator_cron_job.month }}"
    weekday: "{{ curator_cron_job.weekday }}"
    day: "{{ curator_cron_job.day }}"
    hour: "{{ curator_cron_job.hour }}"
    minute: "{{ curator_cron_job.minute }}"
    job: "{{ curator_cron_job.job }}"
    user: "{{ curator_user }}"
    state: present

